### ISSUE TITLE
Confusing resources path

### ISSUE THREAD

**Issue by pskrzypek84** [macieg-b/Patronage_RestAPI_SpringBoot#14]
Paths to some resources should be more intuitive:

    @RequestMapping(method = RequestMethod.POST, value = "/return")
    ResponseEntity<List<Movie>> returnMovies(@RequestBody BorrowView borrowView) {

    @RequestMapping(method = RequestMethod.GET, value = "/return")
    Collection<Movie> readAvailableMovies()

**Comment by macieg-b** [comment]
Resolved by b0a67b7

**Comment by macieg-b** [comment]
Resolved by 890c8f50cbb9aff49c86b43b2db3d4e0320de7dd
